"""initial schema

Revision ID: ce1b86aea89e
Revises: 
Create Date: 2026-07-14 14:37:36.237793
"""
import sqlalchemy as sa
from alembic import op

revision = 'ce1b86aea89e'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('log_events',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('ts', sa.DateTime(timezone=True), nullable=False),
    sa.Column('level', sa.String(length=16), nullable=False),
    sa.Column('logger', sa.String(length=128), nullable=False),
    sa.Column('message', sa.String(length=2048), nullable=False),
    sa.Column('context', sa.JSON(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_log_events_level'), 'log_events', ['level'], unique=False)
    op.create_index(op.f('ix_log_events_ts'), 'log_events', ['ts'], unique=False)
    op.create_table('packs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=128), nullable=False),
    sa.Column('task_type', sa.String(length=32), nullable=False),
    sa.Column('config', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_packs_name'), 'packs', ['name'], unique=True)
    op.create_table('sources',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('pack_name', sa.String(length=128), nullable=False),
    sa.Column('name', sa.String(length=256), nullable=False),
    sa.Column('config', sa.JSON(), nullable=False),
    sa.Column('cadence', sa.String(length=64), nullable=False),
    sa.Column('enabled', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('pack_name', 'name', name='uq_source_pack_name')
    )
    op.create_index(op.f('ix_sources_pack_name'), 'sources', ['pack_name'], unique=False)
    op.create_table('mapping_cache',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('source_id', sa.Integer(), nullable=False),
    sa.Column('schema_hash', sa.String(length=64), nullable=False),
    sa.Column('plan', sa.JSON(), nullable=False),
    sa.Column('mapping_version', sa.String(length=64), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['source_id'], ['sources.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('source_id', 'schema_hash', name='uq_cache_src_schema')
    )
    op.create_index(op.f('ix_mapping_cache_schema_hash'), 'mapping_cache', ['schema_hash'], unique=False)
    op.create_index(op.f('ix_mapping_cache_source_id'), 'mapping_cache', ['source_id'], unique=False)
    op.create_table('runs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('pack_name', sa.String(length=128), nullable=False),
    sa.Column('source_id', sa.Integer(), nullable=True),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('finished_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('tokens_in', sa.Integer(), nullable=False),
    sa.Column('tokens_out', sa.Integer(), nullable=False),
    sa.Column('cost_usd', sa.Float(), nullable=False),
    sa.Column('meta', sa.JSON(), nullable=False),
    sa.ForeignKeyConstraint(['source_id'], ['sources.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_runs_pack_name'), 'runs', ['pack_name'], unique=False)
    op.create_table('drops',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('source_id', sa.Integer(), nullable=False),
    sa.Column('run_id', sa.Integer(), nullable=True),
    sa.Column('drop_date', sa.String(length=32), nullable=False),
    sa.Column('content_hash', sa.String(length=64), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('mapping_version', sa.String(length=64), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['run_id'], ['runs.id'], ),
    sa.ForeignKeyConstraint(['source_id'], ['sources.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('source_id', 'content_hash', name='uq_drop_src_hash')
    )
    op.create_index(op.f('ix_drops_content_hash'), 'drops', ['content_hash'], unique=False)
    op.create_index(op.f('ix_drops_source_id'), 'drops', ['source_id'], unique=False)
    op.create_table('canonical',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('drop_id', sa.Integer(), nullable=False),
    sa.Column('source_id', sa.Integer(), nullable=False),
    sa.Column('run_id', sa.Integer(), nullable=True),
    sa.Column('mapping_version', sa.String(length=64), nullable=False),
    sa.Column('checks_passed', sa.Boolean(), nullable=False),
    sa.Column('low_confidence', sa.Boolean(), nullable=False),
    sa.Column('record', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['drop_id'], ['drops.id'], ),
    sa.ForeignKeyConstraint(['run_id'], ['runs.id'], ),
    sa.ForeignKeyConstraint(['source_id'], ['sources.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_canonical_drop_id'), 'canonical', ['drop_id'], unique=False)
    op.create_index(op.f('ix_canonical_source_id'), 'canonical', ['source_id'], unique=False)
    op.create_table('drift_events',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('source_id', sa.Integer(), nullable=False),
    sa.Column('drop_id', sa.Integer(), nullable=True),
    sa.Column('kind', sa.String(length=16), nullable=False),
    sa.Column('detail', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['drop_id'], ['drops.id'], ),
    sa.ForeignKeyConstraint(['source_id'], ['sources.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_drift_events_source_id'), 'drift_events', ['source_id'], unique=False)
    op.create_table('eval_results',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('run_id', sa.Integer(), nullable=True),
    sa.Column('drop_id', sa.Integer(), nullable=False),
    sa.Column('check_name', sa.String(length=128), nullable=False),
    sa.Column('passed', sa.Boolean(), nullable=False),
    sa.Column('blocking', sa.Boolean(), nullable=False),
    sa.Column('detail', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['drop_id'], ['drops.id'], ),
    sa.ForeignKeyConstraint(['run_id'], ['runs.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_eval_results_drop_id'), 'eval_results', ['drop_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_eval_results_drop_id'), table_name='eval_results')
    op.drop_table('eval_results')
    op.drop_index(op.f('ix_drift_events_source_id'), table_name='drift_events')
    op.drop_table('drift_events')
    op.drop_index(op.f('ix_canonical_source_id'), table_name='canonical')
    op.drop_index(op.f('ix_canonical_drop_id'), table_name='canonical')
    op.drop_table('canonical')
    op.drop_index(op.f('ix_drops_source_id'), table_name='drops')
    op.drop_index(op.f('ix_drops_content_hash'), table_name='drops')
    op.drop_table('drops')
    op.drop_index(op.f('ix_runs_pack_name'), table_name='runs')
    op.drop_table('runs')
    op.drop_index(op.f('ix_mapping_cache_source_id'), table_name='mapping_cache')
    op.drop_index(op.f('ix_mapping_cache_schema_hash'), table_name='mapping_cache')
    op.drop_table('mapping_cache')
    op.drop_index(op.f('ix_sources_pack_name'), table_name='sources')
    op.drop_table('sources')
    op.drop_index(op.f('ix_packs_name'), table_name='packs')
    op.drop_table('packs')
    op.drop_index(op.f('ix_log_events_ts'), table_name='log_events')
    op.drop_index(op.f('ix_log_events_level'), table_name='log_events')
    op.drop_table('log_events')
    # ### end Alembic commands ###
